#!/usr/bin/env bash
# Configures local host file to map localhost to 127.0.0.2 and facebook.com to 8.8.8.8

sed -i 's/127\.0\.0\.1/127\.0\.0\.2/g' /etc/hosts

if grep -q "facebook.com" /etc/hosts; then
    sed -i 's/.*facebook\.com/8.8.8.8 facebook.com/g' /etc/hosts
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
